site_name: ç¬‘ç¬‘çš„ç«™
site_url: https://smilingwayne.github.io/Readingxiaoxiao/

nav:
  - Ë—Ë‹Ëá°”á©šËËŠË—: index.md
  - å“²å­¦:
      - Philosophy/index.md
      - é©¬å…‹æ€ä¸»ä¹‰å“²å­¦:
          - æ¯›: Philosophy/Mao.md
          - åŸºç¡€çŸ¥è¯†: Philosophy/basic.md
          - é©¬å…‹æ€ä¸»ä¹‰å®—æ•™è§‚ç ”ç©¶: Philosophy/Marxism_religion.md
          - è‹è”è§£ä½“ä¸é¢œè‰²é©å‘½: Philosophy/Color_revolution.md

      - å®—æ•™å“²å­¦:
          - åŸºç£æ•™: Philosophy/Christian.md
          - ä¸–ç•Œå®—æ•™: Philosophy/World_religion.md
          - çŠ¹å¤ªäººä¸çŠ¹å¤ªæ•™(ç‰›æ´¥é€šè¯†è¯»æœ¬): Philosophy/Jews.md
          - ç›¸ä¼¼ä¹‹ä¹¦: Philosophy/Book_of_resemblance.md
          - æˆ‘ç†è§£çš„ä¼Šæ–¯å…°æ•™: Philosophy/Religion_culture.md

      - æ–‡æ˜:
          - æ–‡æ˜çš„å†²çªä¸ä¸–ç•Œç§©åºçš„é‡å»º: Philosophy/Collision_civilization.md
          - åæ®–æ°‘ä¸»ä¹‰ä¸ä¸–ç•Œæ ¼å±€(ç‰›æ´¥é€šè¯†è¯»æœ¬): Philosophy/Postcolonialism.md
          - æ°‘æ—å›½å®¶é—´çš„å’Œå¹³ä¸æˆ˜äº‰: Philosophy/Peace_war_in_nation_state.md
          - æ”¿æ²»çš„å†å²ä¸è¾¹ç•Œ: Philosophy/Boundary_politics.md
          - æˆ‘ä»¬æ—¶ä»£çš„ç¤¾ä¼šæ€è€ƒä¸é˜…è¯»ä¸»å¼ : Philosophy/Thoughts_in_our_time.md

      - æ”¿æ²»å“²å­¦:
          - è®ºæ”¿åºœ: Philosophy/Government.md
          - æ”¿æ²»å­¦: Philosophy/Politics.md
          - æ”¿æ²»ç¥å­¦: Philosophy/Theology_politics.md
          - ç¾å›½ç”Ÿæ´»ä¸­çš„åæ™ºä¸»ä¹‰: Philosophy/Anti_intellectual_usa.md
          - ä»¥èµ›äºšä¼¯æ—çš„é—äº§: Philosophy/Legacy_berlin.md
          - ç©†æ–¯æ—ä¸æ¿€è¿›ä¸»ä¹‰: Philosophy/Muslim_radicalism.md
          - åœ£æˆ˜ä¸æ–‡æ˜: Philosophy/Gihad_civilization.md
          - è‰¯çŸ¥å¯¹æŠ—æš´åŠ›: Philosophy/Verse_violence.md
          - æœ‰é—²é˜¶çº§è®º: Philosophy/Leisure_class.md
          - ä¸–ç•Œå¤§å›½å¤–äº¤(US): Philosophy/Diplomacy_us.md

      - å¥³æ€§ä¸»ä¹‰å“²å­¦:
          - æ€§å­¦ä¸‰è®º: Philosophy/Sexuality_freud.md
          - æ€§å­˜åœ¨: Philosophy/Sexuality_existence.md
          - ç¥åœ£çš„æ¬¢çˆ±: Philosophy/Sacred_joy.md
          - ä¸ºå¥³æƒè¾©æŠ¤: Philosophy/Indefense_of_feminism.md
          - æ”¿æ²»å­¦ä¸å¥³æ€§ä¸»ä¹‰: Philosophy/Politics_feminism.md
          - å¥³æƒä¸»ä¹‰ç®€å²(ç‰›æ´¥é€šè¯†è¯»æœ¬): Philosophy/Feminism_brief_history.md

      - ç¾å­¦:
          - ç¾çš„å†ç¨‹: Philosophy/Voyage_of_beauty.md
          - æµªæ¼«ä¸»ä¹‰çš„æ ¹æº: Philosophy/Root_of_romanticism.md

      - äººç±»å­¦/ç¤¾ä¼šå­¦:
          - å€¦æ€ ç¤¾ä¼š: Philosophy/Society_of_fatigue.md
          - ä¹¡åœŸä¸­å›½: Philosophy/Rural_china.md
          - ç¦æŸ¯(ç‰›æ´¥é€šè¯†è¯»æœ¬): Philosophy/Facult.md
          - è¥¿å¤ªå¹³æ´‹ä¸Šçš„èˆªæµ·è€…: Philosophy/Voyagers_western_pacific_ocean.md

      - å…¶ä»–:
          - å“²æ€ä¸æµ·â€”â€”ä¸€éƒ¨è¯—æ„çš„å“²å­¦éšç¬”: Philosophy/Phi_and_sea.md
          - ç¦æŸ¯(ç‰›æ´¥é€šè¯†è¯»æœ¬): Philosophy/Facult.md
          - å®ç”¨ä¸»ä¹‰: Philosophy/Pragmatism.md
          - äºšé‡Œå£«å¤šå¾·çš„ä¸–ç•Œ(ç‰›æ´¥é€šè¯†è¯»æœ¬): Philosophy/World_of_aristotle.md

  - æ–‡å­¦:
      - Literature/index.md
      - è¯—æ­Œ:
          - Poems/index.md
          - å¤–å›½è¯—:
              # - Poems/index.md
              - æ•£è½ç¢ç‰‡: Poems/Middle_east.md
              - æ„¤æ€’ä¸ç¥ç§˜: Poems/Anger_and_mystery.md
              - æ¶ä¹‹èŠ±: Poems/Fleurs_du_mal.md
              - æ˜¯ä½ åœ¨æ­Œå”±ï¼Ÿæ˜¯æˆ‘åœ¨éæƒ³: Poems/Yesenin.md
              - ç©¿è£¤å­çš„äº‘: Poems/Mayakovsky.md
              - å¢æµå¡”å°¼äºšäººä¹‹æ­Œ: Poems/Luzitania.md
              - ç”Ÿå‘½ä¸å¸Œæœ›ä¹‹æ­Œ: Poems/Poems_de_life_hope.md
              - ä¼Šåˆ©äºšç‰¹: Poems/Illiad.md
              - å¾·å›½ï¼Œä¸€ä¸ªå†¬å¤©çš„ç«¥è¯: Poems/German_winter_fairytale.md
              - åç‰¹ä¼¯é›·æ•…äº‹é›†: Poems/Canterbery.md
              - æˆ‘ç”¨å¤å…¸çš„æ–¹å¼çˆ±è¿‡ä½ : Poems/Emily.md

              - ç–‘é—®é›†: Poems/Collections_of_doubt.md
          - ä¸­å›½è¯—:
              - è¾›å¼ƒç–¾è¯: Poems/Xinqiji_ci.md
              - æœ¨å¿ƒè¯—é€‰: Poems/Muxin.md
              - æœˆå…‰åœåœ¨å·¦æ‰‹ä¸Š: Poems/Moonlight_left_hand.md
      - æˆå‰§:
          - Plays/index.md
          - æˆå‰§:
              - æµ®å£«å¾·: Plays/Faust.md
              - å¹¿å²›ä¹‹æ‹: Plays/Hiroshima.md
              - çˆ±çš„å¾’åŠ³: Plays/Loves_labors_lost.md
              - å¥¥èµ›ç½—: Plays/Othello.md
              - éº¦å…‹ç™½: Plays/Macbeth.md
              - ğŸ’å“ˆå§†é›·ç‰¹: Plays/Hamlet.md
              - äº¨åˆ©å››ä¸–: Plays/HenryIV.md
              - ç†æŸ¥äºŒä¸–: Plays/Richard_II.md
              - æš´é£é›¨: Plays/Storms.md
              - æµ·é¸¥: Plays/Seagull.md
              - ç¾ç‹„äºš: Plays/Media.md
              - ç‰¡ä¸¹äº­: Plays/Mu_dan_ting.md
              - æ¡ƒèŠ±æ‰‡: Plays/Tao_hua_shan.md
              - é“¸å‰‘Â·å“ˆå§†é›·ç‰¹: Plays/Swords_hamlet.md
              - ç½—å¯†æ¬§ä¸æœ±ä¸½å¶: Plays/Romeo_juliet.md
              - é•¿æ˜: Plays/Long_daylight.md
          - å½±è§†:
              - åˆ‡è…¹: Plays/Seppuku.md
              - æ…•å°¼é»‘: Plays/Munich.md
              - ç²¾ç–²åŠ›å°½: Plays/Exhausted.md
              - åœ°å¿ƒå¼•åŠ›: Plays/Gravity.md
              - äº”è‡³ä¸ƒæ—¶çš„å…‹è±å¥¥: Plays/Cleo.md
              - ä¸­å›½å§‘å¨˜: Plays/La_chinioise.md
              - æ— ä¸»ä¹‹ä½œ: Plays/Werk_ohne_autor.md

      - éšç¬”:
          - Literature/Essay/index.md
          - å°äºä¸€: Literature/Essay/Less_than_one.md
          - äºŒæ‰‹æ—¶é—´: Literature/Essay/Second_hand_time.md
          - è®°å¿†è®°å¿†: Literature/Essay/Remember_memory.md
          - ç«çš„è®°å¿†: Literature/Essay/Memory_fire.md
          - äººé—´é£Ÿç²®: Literature/Essay/Life_food.md
          - ç‰›æ£šæ‚å¿†: Literature/Essay/Cowshed_memo.md
          - æ¾¡å ‚ä¸ç‰‡åœº: Literature/Essay/Bath_house.md
          - å¾€äº‹ä¸éšæƒ³: Literature/Essay/Memory_thoughts.md
          - ä¸­å›½æ–‡å­¦å¸¸è¯†: Literature/Essay/Literature_knowledge.md
          - è±¡å¾ä¸»ä¹‰ç¢ç‰‡: Literature/Essay/Impressionalism_pieces.md
          - åšå°”èµ«æ–¯è°ˆè¯å½•: Literature/Essay/Borges.md
          - åˆ«èµ°ï¼Œä¸‡ä¸€å¥½ç¬‘å‘¢: Literature/Essay/Stay.md
          - é˜…è¯»æ˜¯ä¸€åº§éšèº«æºå¸¦çš„é¿éš¾æ‰€: Literature/Essay/Reading_shelter.md
          - ç¦…ä¸æ‘©æ‰˜è½¦ç»´ä¿®è‰ºæœ¯: Literature/Essay/Zen_motor_maintanence.md
      - æ–‡è®º:
          - Literature/Literacy/index.md
          - é­æ™‹ç„å­¦: Literature/Literacy/Xuan_xue.md
          - è¥¿æ–¹æ­£å…¸: Literature/Literacy/Western_classic.md
          - å·´é»è¯„è®º: Literature/Literacy/Paris_review.md
          - ä½œå®¶ç¬”è®°: Literature/Literacy/Writers_notes.md
          - å¤©æœé¥è¿œ: Literature/Literacy/Dynasty.md
          - æ³•è¯­æ–‡å­¦: Literature/Literacy/French_literature.md
          - æ–‡å­¦å›å¿†å½•: Literature/Literacy/Literature_memo.md
          - å¥³äººçš„é£ŸæŒ‡: Literature/Literacy/Womens_index_finger.md
          - æ²‰é»˜çš„å¤§å¤šæ•°: Literature/Literacy/Silent_most.md
          - æ‰¹åˆ¤æ€§æ€ç»´çš„å½¢æˆ: Literature/Literacy/Formation_critical_thinking.md
          - å¤©çœŸçš„å’Œæ„Ÿä¼¤çš„å°è¯´å®¶: Literature/Literacy/Naive_novlist.md
          - æµªæ¼«ä¸»ä¹‰(ç‰›æ´¥é€šè¯†è¯»æœ¬): Literature/Literacy/Romanticism.md
          - æ‹‰ä¸ç¾æ´²æ–‡å­¦(ç‰›æ´¥é€šè¯†è¯»æœ¬): Literature/Literacy/Latin_america_literature.md
      - å°è¯´:
          - Literature/Novel/index.md
          - è›™: Literature/Novel/Frog.md
          - é¢çº±: Literature/Novel/Veil.md
          - é¼ ç–«: Literature/Novel/Plague.md
          - æœé—»é“: Literature/Novel/Zhao_wen_dao.md
          - é‡æ£•æ¦ˆ: Literature/Novel/Wild_palm.md
          - åŒåŸè®°: Literature/Novel/Stories_of_two_cities.md
          - ç½—ç”Ÿé—¨: Literature/Novel/Rashomon.md
          - åæ°451: Literature/Novel/Fahrenheit_451.md
          - ã€Š1984ã€‹: Literature/Novel/1984.md
          - æ’’é©¬å°”ç½•: Literature/Novel/Samarkhan.md
          - ç”Ÿæ­»ç–²åŠ³: Literature/Novel/Forever_fatigue.md
          - äº”å·å± åœº: Literature/Novel/Slaughterhouse_five.md
          - æ²‰é»˜çš„ç—…äºº: Literature/Novel/Silent_patient.md
          - ä¸‰ä¸ªç«æªæ‰‹: Literature/Novel/Three_riflers.md
          - é›ªè½é¦™æ‰æ ‘: Literature/Novel/Snow_falls.md
          - æ½˜ç¥çš„è¿·å®«: Literature/Novel/Labyrinth_pan.md
          - è¾¾èŠ¬å¥‡å¯†ç : Literature/Novel/Davinci_code.md
          - æ ¼åˆ—ä½›æ¸¸è®°: Literature/Novel/Gulliver.md
          - å¤±æ˜ç—‡æ¼«è®°: Literature/Novel/Ensaio_sobre_a_cegueira.md
          - ç˜Ÿç–«å¹´çºªäº‹: Literature/Novel/Pandemic_era.md
          - å¡æ‹‰é©¬ä½å¤«å…„å¼Ÿ: Literature/Novel/Kara_Mazov_brothers.md
          - ä¸œæ–¹å¿«è½¦è°‹æ€æ¡ˆ: Literature/Novel/Oriental_express.md
          - å°¼ç½—æ²³ä¸Šçš„æƒ¨æ¡ˆ: Literature/Novel/Tragedy_niro.md
          - äº†ä¸èµ·çš„ç›–èŒ¨æ¯”: Literature/Novel/Gatsby.md
          - çº¢ç«ç‘°ä¸ç™½ç«ç‘°: Literature/Novel/Red_roses_white_roses.md
          - æŸ¥ä»¤åå­—è¡—84å·: Literature/Novel/Charline_84.md

  - å†å²:
      - History/index.md
      - å°å°¼ETC: History/Indonesia.md
      - å¸Œè…Šç¬”è®°: History/Greece.md
      - éæ´²ç¬”è®°: History/Africa.md
      - ä¸­äºšç¬”è®°: History/Mid_asia.md
      - è‹è”ç¬”è®°: History/Soviet_union.md
      - è®°å¿†ä¹‹åœº: History/Field_of_memory.md
      - æ–­å¤´ç‹å: History/Marie_antoinette.md
      - æ¬§ç½—å·´ç¬”è®°: History/Europe.md
      - æ³•å…°è¥¿ç¬”è®°: History/France.md
      - é˜¿æ‹‰ä¼¯ç¬”è®°: History/Arabians.md
      - è’è¯åŒ»å­¦å²: History/Ridiculous_medics.md
      - ç½—é©¬å¸å›½ç®€å²: History/Roman_empire_brief_history.md
      - é˜¿æ‹‰ä¼¯ä¼Šæ–¯å…°æ–‡åŒ–å²: History/Arabian_islamic_history.md
      - æ³•å›½èµ„äº§é˜¶çº§å²(ä¸Š): History/Bourgeoisie.md
      - åˆ©å¥¥æ³¢å¾·å›½ç‹çš„é¬¼é­‚: History/King_leopolds_ghost.md
      - æ³•å›½çŸ¥è¯†åˆ†å­çš„ä¸–çºª: History/Century_of_intellects_in_France.md
      - æ‹‰ä¸ç¾æ´²è¢«åˆ‡å¼€çš„è¡€ç®¡: History/Latin_american_blood.md
      - ä¸€ä¸ªå¤§å›½çš„å´›èµ·ä¸å´©æºƒ: History/Rise_and_fall.md
      - ç°ä»£æ—¥æœ¬(ç‰›æ´¥é€šè¯†è¯»æœ¬): History/Modern_japan.md
      - ä¸œé£â€”â€”æ³•å›½çŸ¥è¯†åˆ†å­ä¸60å¹´ä»£çš„é—äº§: History/Eastern_wind.md
  - è‰ºæœ¯:
      - Arts/index.md
      - æ‹‰æ–å°”å‰æ´¾çš„æ¢¦: Arts/Pre_Raphael.md
      - é»‘å¤œçš„è´è¶: Arts/Butterfly_at_night.md
      - å·¦å²¸,ä»äººæ°‘é˜µçº¿åˆ°å†·æˆ˜ä½œå®¶: Arts/Left_bank.md
      - éä¸»æµè‰ºæœ¯å²: Arts/Art_history_unfashioned.md
      - å·´é»ç¥è¯â€”â€”ä»å¯è’™è¿åŠ¨åˆ°è¶…ç°å®ä¸»ä¹‰: Arts/Parisian_myth.md
      - è‰ºæœ¯å¼•å¯¼äººç”Ÿâ€”â€”å¾·æ‹‰å…‹æ´›ç“¦ç§äººæ—¥è®°: Arts/Delacroix.md
      - æ³•å›½åˆ¶é€ â€”â€”æ³•å›½æ–‡åŒ–å…³é”®è¯: Arts/Made_in_French.md
      - è¾¾è¾¾å’Œè¶…ç°å®ä¸»ä¹‰: Arts/Dada_surrealism.md
      - è´å¤šèŠ¬çš„éª°å­: Arts/Beethoven.md
      - çˆ±çš„è‰ºæœ¯: Arts/Arts_of_love.md
      - è‰ºæœ¯çš„æ•…äº‹: Arts/Stories_of_art.md
      - æ–‡è‰ºå¤å…´æ—¶æœŸçš„è‰ºæœ¯: Arts/Art_renaissance.md
      - ç°ä»£ä¸»ä¹‰: Arts/Modernism.md
      - ç¢ç‰‡è‰ºæœ¯: Arts/Pieces.md
  - è€ƒç ”:
      - æˆ‘çš„è§„åˆ’: yan/yanPlans.md
      - æˆ‘çš„ç”¨ä¹¦: yan/yanBooks.md
      - é—²èŠ: yan/yanTalks.md
  - æƒ³/åœ¨åšçš„äº‹:
      - ä¹¦: ToDo/ToRead.md
      - æœ¯: ToDo/ToCode.md
  - å­¦ä¹ :
      - æˆ‘çš„2022: Study/My2022.md
      - çº¿æ€§ä»£æ•°:
          - chapter1: Study/LinearAlgebra/Chapter1.md
          - chapter2: Study/LinearAlgebra/Chapter2.md
      - è¿ç­¹å­¦: Study/OperationsResearch1.md
      - macOSå­—ä½“æ¨è: Study/Markdown.md
      - å¹»æ–¹ç®—æ³•: Study/MagicSquare.md
      - Swift: Study/Swift/CS193p1.md
      - Markdownè¯­æ³•1: Study/MarkdownSyntax1.md
      - LaTexè¯­æ³•: Study/LatexNotes.md
      - ä¾›åº”é“¾ç®¡ç†:
          - ä¸‰ç§å·¥å‚é€‰å€æ¨¡å‹(Chapter_5.4): Study/Supplychain/Supplychain1.md
          - æ—¶é—´åºåˆ—é¢„æµ‹ï¼šé™æ€æ–¹æ³•(Chapter_7.5.1): Study/Supplychain/SupplyChain13.md
          - æ—¶é—´åºåˆ—é¢„æµ‹æ¨¡å‹ä¸æ¡†æ¶ï¼šARMA/Winter(Chapter_7.5/7.6): Study/Supplychain/SupplyChain3.md
          - ç»æµè®¢è´§æ‰¹é‡æ¨¡å‹(EOQ)(Chapter_11.3): Study/Supplychain/SupplyChain4.md
          - EOQæ¨¡å‹çš„è®¢è´§é‡ç¡®å®šä¸å‘¨æœŸç›˜ç‚¹(Chapter_11.3.2): Study/Supplychain/SupplyChain9.md
          - ä¾›åº”é“¾ç»¼åˆè®¡åˆ’ç­–ç•¥I(Chapter_8.4): Study/Supplychain/SupplyChain7.md
          - ä¾›åº”é“¾ç»¼åˆè®¡åˆ’ç­–ç•¥IIï¼šæ¡ˆä¾‹åˆ†æ(Chapter_8.5): Study/Supplychain/SupplyChain11.md
          - è§„æ¨¡ç»æµç®¡ç†ï¼šæ•°é‡æŠ˜æ‰£I(Chapter_11.4): Study/Supplychain/SupplyChain5.md
          - è§„æ¨¡ç»æµç®¡ç†ï¼šæ•°é‡æŠ˜æ‰£II(Chapter_11.4): Study/Supplychain/SupplyChain8.md
          - è¿è¥ç®¡ç†ï¼šæ’é˜Ÿè®º: Study/Supplychain/SupplyChain6.md
          - å®‰å…¨åº“å­˜ï¼šåŸºäºç»™å®šç­–ç•¥(Chapter_12.2): Study/Supplychain/SupplyChain10.md
          - å®‰å…¨åº“å­˜ï¼šèšé›†/ä¾›ç»™ä¸ç¡®å®š/é›¶ä»¶çš„æƒ…å†µ(Chapter_12.3): Study/Supplychain/SupplyChain12.md
          - æœ€ä¼˜å¯è·å¾—æ€§æ°´å¹³çš„ç¡®å®š: Study/Supplychain/SupplyChain14.md

      - è®ºæ–‡: Study/Undergraduate_essay.md

site_author: SmilingWayne

repo_name: SmilingWayne/Readingxiaoxiao
repo_url: https://github.com/SmilingWayne/Readingxiaoxiao

theme:
  locale: en
  name: material
  #   custom_dir: overrides
  # custom_dir: /docs/stylesheets/
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.sections
    # - navigation.expand
    # - navigation.top
    - navigation.indexes
    # - content.action.edit
    # - content.action.view

  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  #   - git-revision-date-localized:
  #       type: datetime
  #       custom_format: "%d. %B %Y"
  #       timezone: Asia/Shanghai
  #       locale: en
  #       fallback_to_build_date: false
  #       enable_creation_date: true
  #       exclude:
  #         - index.md
  #       enabled: true

  - search:
      lang: ja

markdown_extensions:
  - admonition
  - meta
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: âš“ï¸

extra:
  social:
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/wang-zhi-xiao-49-5
    - icon: fontawesome/brands/github
      link: https://github.com/SmilingWayne
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/6025785811

copyright: Copyright &copy; 2001 - 2023 xiaoxiaoWayne
